# Generated by Django 3.0.3 on 2020-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
