# Generated by Django 3.0.3 on 2020-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
