# Generated by Django 3.0.3 on 2020-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_award_feature_highlight_pricing_question_single_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazing_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('data', models.TextField(max_length=255)),
                ('text', models.TextField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('clas', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('profile', models.CharField(max_length=255)),
                ('data', models.TextField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('data', models.TextField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('profile', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
