# Generated by Django 3.0.3 on 2020-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_amazing_feature_benefit_icon_project_team_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
