# Generated by Django 3.0.3 on 2020-08-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
