# Generated by Django 3.0.3 on 2020-08-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_message_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Left_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=255)),
                ('office', models.TextField(max_length=255)),
                ('copyrigh', models.TextField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Left_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('text', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=255)),
                ('imagea', models.ImageField(upload_to='images/')),
                ('data', models.TextField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
