# Generated by Django 3.0.3 on 2020-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contact_footer_icon_left_data_left_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_form',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
