# Generated by Django 3.0.3 on 2020-08-13 12:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_highlight',
            name='data',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
