# Generated by Django 3.0.3 on 2020-08-13 12:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200813_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_highlight',
            name='data',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
